### ISSUE TITLE
sunos unsupported

### ISSUE THREAD

**Issue by hayhv** [LinusU/node-cachedir#11]
Currently unsupported on sunos. Could you support make on  sunos

**Comment by travispaul** [comment]
@hayhv NetBSD also (see: #12), I think the maintainer is on a long vacation (@LinusU).

Honestly, I think it'd make more sense to try and fallback to posix if the OS is undetected instead of special casing each one.

**Comment by LinusU** [comment]
Sorry for the late reply, my inbox has been overflowing after getting back from a long vacation 🙈 

I've added support for `aix`, `netbsd`, and `sunos`, and also added a fallback with a warning to posix:

> (node:33295) [cachedir] Warning: the platform "foobar" is not currently supported by node-cachedir, falling back to "posix". Please file an issue with your platform here: https://github.com/LinusU/node-cachedir/issues/new

This is all released as 2.3.0 🚀
