### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by simhnna** [LinusU/node-cachedir#17]
Hi,

thanks for the lib. I'm using it in a typescript project and found out that there are no types. Would you be open to convert the project to typescript or adding the bundling types in the releases on npm?

If not I'd add them to DefinitelyTyped but wanted to ask here first

**Comment by LinusU** [comment]
Fixed in f982c13a224ba306f16bb1e0f5b1aa7a60b837b4, released as [🚢 2.4.0 / 2023-07-24](https://github.com/LinusU/node-cachedir/releases/tag/v2.4.0)
