### ISSUE TITLE
FreeBSD unsupported

### ISSUE THREAD

**Issue by duncan-bayne** [LinusU/node-cachedir#6]
Currently, node-cachedir doesn't support FreeBSD.

```
var implementation = (function () {
  switch (os.platform()) {
    case 'android':
    case 'linux': return linux
    case 'darwin': return darwin
    case 'win32': return win32
    default: throw new Error('Your OS is currently not supported by node-cachedir.')
  }
}())
```

I'd love to submit a patch to add FreeBSD support, but rather than adding another special case, perhaps we could change the logic here a bit?

Thinking I could do something like:

```
var implementation = (function () {
  switch (os.platform()) {
    case 'darwin': return darwin
    case 'win32': return win32
    default: return posix 
  }
}())
```

... and have the `posix()` function attempt to find the `XDG_CACHE_HOME` environment variable, fall back to using `homedir()`, and if _that_ doesn't work, only then raise the unsupported error.

Thoughts?

**Comment by LinusU** [comment]
With the rise of Fuschia, Redox and other new OSes that are not necessarily based on Unix, I think it would be nice to err on the side of caution and keep the current approach...

Could be nice to rename the `linux` function to `posix` though 👍

**Comment by duncan-bayne** [comment]
Okay, makes sense.  Shall I open a PR?

**Comment by LinusU** [comment]
Yes please ☺️
